### ISSUE TITLE
UPE Auth Server

### ISSUE THREAD

**Issue by vitorvicente** [BUUPE/homepage#45]
Implement BU Login Features

**Comment by ROODAY** [comment]
Making a UPE auth server would be useful as then we wont need a server to host this (or any of our firebase apps). they would just need to query that auth server.

https://firebase.google.com/docs/auth/web/custom-auth

**Comment by vitorvicente** [comment]
For the time being I'm just going to use an internal login system to match with our account DB, and closing this issue, sometime in the future I'll revisit this and see what can be done about the Auth Server
